{% set python_min = "3.11" %}
{% set version = "0.2.0" %}

package:
  name: fractal-tasks-utils
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/f/fractal-tasks-utils/fractal_tasks_utils-{{ version }}.tar.gz
  sha256: 9ee8c775599f5658e4ae4825372f767ac3a50fafd62ed76e76b9dd202d789495

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - pandas
    - python >={{ python_min }}
    - ngio >=1.1.0,<1.2
    - pydantic
    - numpy
    - scikit-image

test:
  imports:
    - fractal_tasks_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/fractal-tasks-utils/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: General utilities for building Fractal tasks.

extra:
  recipe-maintainers:
    - lorenzocerrone
    - jluethi
    - tcompa
